-- Active: 1698904464779@@127.0.0.1@3306@business_db
--Write a SQL query to retrieve the total revenue generated by each product category. 
--Display the category name along with the total revenue in descending order of the revenue.

SELECT c.name, SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM categories c
INNER JOIN products p ON c.id = p.category_id
INNER JOIN order_items oi ON p.id = oi.product_id
GROUP BY c.name
ORDER BY total_revenue DESC;
